[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
pulse_strike = "4ZHAWqT8mQvowMnt4LEA282koU1FhdUd9RL1htfmbg8V"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
